from sqlmodel import SQLModel, Field
from datetime import time

class GreenhouseSettings(SQLModel, table=True):
    id: int = Field(primary_key=True)
    node_id: int = Field(default=0)
    upper_temperature: float = Field(default=0.0)
    lower_temperature: float = Field(default=0.0)
    upper_humidity_windows: int = Field(default=0)
    window_open_step: int = Field(default=0)
    window_sleep_step: int = Field(default=0)
    humidity_windows_sleep_step: int = Field(default=0)
    humidity_windows_cycle_await: int = Field(default=0)
    windows_total_closing: int = Field(default=0)
    windows_open_rain: int = Field(default=0)
    curtains_open_humidity: int = Field(default=0)
    humidity_curtains_sleep_step: int = Field(default=0)
    humidity_curtains_cycle_await: int = Field(default=0)
    upper_humidity_curtains: int = Field(default=0)
    curtains_total_closing: int = Field(default=0)
    curtains_open_after_closing: int = Field(default=0)
    upper_light: int = Field(default=0)
    lower_light: int = Field(default=0)
    main_heat_start_temp: float = Field(default=0.0)
    main_heat_stop_temp: float = Field(default=0.0)
    main_heat_max_time: int = Field(default=0)
    main_heat_pause_time: int = Field(default=0)
    main_heat_humidity_start: float = Field(default=0.0)
    main_heat_humidity_stop: float = Field(default=0.0)
    main_heat_humidity_max_time: int = Field(default=0)
    main_heat_humidity_pause_time: int = Field(default=0)
    secondary_heat_start_temp: float = Field(default=0.0)
    secondary_heat_stop_temp: float = Field(default=0.0)
    secondary_heat_max_time: int = Field(default=0)
    secondary_heat_pause_time: int = Field(default=0)
    secondary_heat_humidity_start: float = Field(default=0.0)
    secondary_heat_humidity_stop: float = Field(default=0.0)
    secondary_heat_humidity_max_time: int = Field(default=0)
    secondary_heat_humidity_pause_time: int = Field(default=0)
    day_start: time = Field(default=time(0, 0))  # Defaulting to midnight
    night_start: time = Field(default=time(0, 0))  # Defaulting to midnight
    window_manual_operation: int = Field(default=0)
    curtains_manual_operation: int = Field(default=0)
    main_heating_manual_operation: int = Field(default=0)
    secondary_heating_manual_operation: int = Field(default=0)
